name: Update Stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Stats
        uses: kyechan99/velog-stats@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 2ca0ced45ecf85f7e6ac1fbf04b14ac5
          VELOG_ID: kyechan99
          TIMEZONE: Asia/Seoul
